// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function OrganizeFiles(arg1) {
  return window['go']['main']['App']['OrganizeFiles'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
