// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHistory():Promise<Array<main.FileRecord>>;

export function GetStats():Promise<main.StatsResponse>;

export function OrganizeFiles(arg1:string):Promise<main.OrganizeResult>;

export function SelectFolder():Promise<string>;
